config/routes.rb
Failboard::Application.routes.draw do
  
  get "albums/new"

  get "users/show"

  break if ARGV.join.include? 'assets:precompile'
  ActiveAdmin.routes(self)

  
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :albums do
  get 'tags/:tag', to: 'fails#index', as: :tag
  resources :fails do
      member do
        post :up_vote
      end
  end

 
  end

  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'albums#index'

  match '/about',     to: 'pages#about'
  match '/fails',     to: 'fails#index'
  match '/new-fail',  to: 'fails#new'
  match 'users/:id',  to: 'users#show', :as => :user
  match '/new-album', to: 'albums#new'

end

app/models/fail.rb
class Fail < ActiveRecord::Base
  attr_accessible :description, :image, :remote_image_url, :fail_title, :tag_list, :processed, :youtube_url, :album_id
  make_voteable
  acts_as_taggable

  belongs_to :album

  mount_uploader :image, ImageUploader
 

	validates            :description, length: { :maximum => 200 }
	validates            :album_id, presence: true
	validates            :image, presence: true
  validates            :fail_title, presence: true, length: { :maximum => 50 }
  validate 			       :maximum_amount_of_tags


  	def maximum_amount_of_tags
  		number_of_tags = tag_list_cache_on("tags").uniq.length
  		errors.add(:base, "Please only add up to 5 tags") if number_of_tags > 5
  	end

    before_save :update_attachment_attributes
   
    def update_attachment_attributes
      if image.present? && image_changed?
        self.content_type = image.file.content_type
        self.file_size = image.file.size
      end
    end

    def next
    	user.fails.where("id > ?", id).order("id ASC").first
  	end

  	def prev
    	user.fails.where("id < ?", id).order("id DESC").first
  	end


end

app/controllers/Fails_controller.rb
class FailsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /fails
  # GET /fails.json
  def index
    if params[:tag]
     @fails = Fail.tagged_with(params[:tag]).page params[:page]
    else
     @fails = Fail.order("created_at desc").page params[:page]
    end


    @tags = Fail.tag_counts_on(:tags, :limit => 30, :order => "count desc")

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @fails }
    end
  end

  # GET /fails/1
  # GET /fails/1.json
  def show
    @fail = Fail.find(params[:id])
    @fails_count = Fail.count
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fail }
    end
  end

  # GET /fails/new
  # GET /fails/new.json
  def new
    @fail = Fail.new(:album_id => params[:album_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fail }
    end
  end

  # GET /fails/1/edit
  def edit
    @fail = current_user.albums.fails.find(params[:id])
  end

  # POST /fails
  # POST /fails.json
  def create
    @fail = Fail.new(params[:fail])

    respond_to do |format|
      if @fail.save
        format.html { redirect_to  @fail.album,  notice: 'You added a new photo!' }
        format.json { render json: @fail, status: :created, location: @fail }
      else
        format.html { render action: "new" }
        format.json { render json: @fail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fails/1
  # PUT /fails/1.json
  def update
    @fail = current_user.fails.find(params[:id])

    respond_to do |format|
      if @fail.update_attributes(params[:fail])
        format.html { redirect_to @fail, notice: 'fail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fails/1
  # DELETE /fails/1.json
  def destroy
    @fail = current_user.fails.find(params[:id])
    @fail.destroy

    respond_to do |format|
      format.html { redirect_to fails_url }
      format.json { head :no_content }
    end
  end

  def up_vote
    @fail = Fail.find params[:id]
    current_user.up_vote(@fail)
    redirect_to fail_path(@fail)
  end

end

app/helpers/fails_helper.rb
module FailsHelper

def youtube_embed(youtube_url)
  if youtube_url[/youtu\.be\/([^\?]*)/]
    youtube_id = $1
  else
    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
    youtube_id = $5
  end

  %Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
end

def parse_youtube url
   regex = /^(?:http:\/\/)?(?:www\.)?\w*\.\w*\/(?:watch\?v=)?((?:p\/)?[\w\-]+)/
   url.match(regex)[1]
end

end

app/views/fails/_fail.html.erb
<div class="box">

		<center><img src="https://s3.amazonaws.com/failboard/tack.png" id="tack" /></center><br />

	<center>
		<strong><p style="font-size: 16px;"><u><%= @album.fail.fail_title %></u></p></strong>


		<%= link_to (image_tag fail.image), fail %>

	</center>
	<hr></hr>
     <p class="description"style="font-size: 14px;">
      	<%= fail.description %>
 	 </p>
 	 <br />
 	 <% if fail.tag_list.any? %>
 	 <p>Tags: <%= raw fail.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
 	 <% end %>
 	 <br />
 	 <p>

 	 		 	 	
	 </p>
	<div class="pull-right">
		<% if fail.up_votes > 0 %>
				<center>
					<% if fail.up_votes == 1 %>
							<p><%= link_to "#{fail.up_votes} LOL", fail %></p>
						<% else %>
							<p><%= link_to "#{fail.up_votes} LOLs", fail %></p>
					<% end %>
				</center>
		<% end %>
	</div>
  Posted by  #link_to fail.user.name, fail.user

</div>

app/views/fails/_form.html.erb
<div class="formfail">
  <center>
    <% if params[:action] == "new" %>
         <h1>New Photo</h1><br />
    <% else %>
         <h1>Edit Photo</h1><br />
    <% end %>
    
      <%= simple_form_for(@fail) do |f| %>

            <%= f.error_notification %>
            <%= f.full_error :image_file_size, class: "alert alert-error" %>
            <%= f.full_error :image_content_type, class: "alert alert-error" %>


            <strong><p>Title of the Photo</p></strong>
            <%= f.input :fail_title, label: "" %><br />
          
            
            <strong><p>Upload a Photo</p></strong>
            <%= f.input :image, label: "" %><br />


            <%= f.input :description, as: :text, input_html: { rows: "3"} %>
           
            <strong><p>Photo Tags (Serarate by comma!)</p></strong>
            <%= f.input :tag_list %>

            <div class="form-actions">
              <%= f.button :submit, class: "btn btn-primary" %>
            </div>

      <% end %>
  </center>
</div>

app/views/fails/create.js.erb
<% if @fail.new_record? %>
  alert("Failed to upload painting: <%= j @fail.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#paintings").append("<%= j render(@fail) %>");
<% end %>

app/views/fails/edit.html.erb
<%= render 'form' %>

app/views/fails/index.html.erb
<%= render 'pages/home' %>

<% if !user_signed_in? %>
<br />
<center><%= image_tag("https://s3.amazonaws.com/failboard/failboard.png") %></center><br />
<% end %>
	<center>
		<div class="boxthree">
				<div id="tag_cloud">
					<center><img src="https://s3.amazonaws.com/failboard/tack.png" id="tack" /></center>
					<h2>Most Popular Tags</h2>
				  <% tag_cloud @tags, %w{s m l} do |tag, css_class| %>
				    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
				  <% end %>
				</div>
		</div>
	</center>


<div id="fails">
  <%= render @fails %>
</div>

<%= paginate @fails %>

app/views/fails/index.js.erb
$boxes = $('<%= j render(@fails) %>');
$('#fails').append( $boxes ).imagesLoaded( function(){
	$('#fails').masonry( 'reload');
});
<% if (@fails.current_page < @fails.num_pages) %>	
	setTimeout(function(){
		$('.pagination').replaceWith('<%= j paginate(@fails) %>');
	},1000);						
<% else %>
	$('.pagination').remove();
<% end %>

app/views/fails/new.html.erb
<%= render 'form' %>

app/views/fails/show.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '534777629886814', // App ID from the App Dashboard
      channelUrl : '//www.infinite-bastion-8143.herokuapp.com', // Channel File for x-domain communication
      status     : true, // check the login status upon init?
      cookie     : true, // set sessions cookies to allow your server to access the session?
      xfbml      : true  // parse XFBML tags on this page?
    });

    // Additional initialization code such as adding Event Listeners goes here

  };

//added in a comment
  // Load the SDK's source Asynchronously
  // Note that the debug version is being actively developed and might 
  // contain some type checks that are overly strict. 
  // Please report such bugs using the bugs tool.
  (function(d, debug){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
     ref.parentNode.insertBefore(js, ref);
   }(document, /*debug*/ false));
</script>


<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=534777629886814";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



<div class="row">
	<div class="span6 offset2">
		<div class="boxtwo">
			<p>
				<center>

				  <b><u><p style="font-size:22px;"><%= @album.fail.fail_title %></p></u></b>
				  <br />
				  <br />

				  <%= render 'fails/fail' %>

				  <br />
				  <br />
				  <div class="sharetable">
					<table border="0" bordercolor="" style="background-color:" width="70%" cellpadding="7" cellspacing="5">
						<tr>
							
							<td>
								<div class="arrow_box"><%= @fail.up_votes %></div><br />
								<% if current_user.voted?(@fail) == false %>
									<%= link_to "LOL", up_vote_fail_url(@fail), :method => :post, class: "btn btn-small btn-primary" %>
								<% else %>
									<%= image_tag("https://s3.amazonaws.com/failboard/loldone.png") %>
								<% end %>
							</td>

							<td><%= link_to image_tag("https://s3.amazonaws.com/failboard/fbshareicon.png"), "https://www.facebook.com/dialog/feed?app_id=534777629886814&link=http%3A%2F%2Finfinite-bastion-8143.herokuapp.com%2Ffails%2F#{@fail.id}&picture=#{@fail.image_url}&Signature=iMcsNessMId1CPwCnD%2BY2D8C6W4%3D&Expires=1362818901&caption=#{@fail.fail_title}&description=#{@fail.description}&redirect_uri=http%3A%2F%2Finfinite-bastion-8143.herokuapp.com%2Ffails%2F#{@fail.id}", :target => "_blank" %></td>

							<td><a href="https://twitter.com/share" class="twitter-share-button" data-text="#FAIL" data-hashtags="Failboard">Tweet</a></td>

							<td><a data-pin-config="above" href="//pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" ><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a></td>

							<td><a href="http://www.tumblr.com/share" title="Share on Tumblr" target="_blank" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:81px; height:20px; background:url('http://platform.tumblr.com/v1/share_1.png') top left no-repeat transparent;">Share on Tumblr</a></td>

							<td><a href="http://www.reddit.com/submit" target="_blank" onclick="window.location = 'http://www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"><img src="http://www.reddit.com/static/spreddit7.gif" alt="submit to reddit" border="0" /></a></td>
						</tr>
					</table>
				</div>
					<br />
					
					<% if @fail.tag_list.any? %>
					<p>Tags: <%= @fail.tag_list %></p>
					<br /><br />
					<% end %>
				  <p style="font-size: 18px;"><%= @fail.description %></p><br /><br />


				  	<% if @fail.id != Fail.first.id %>
						<div class="pull-left">
							<%= link_to image_tag("https://s3.amazonaws.com/failboard/previousfail.png"), @fail.prev %>
						</div>
					<% else %>
						<div class="pull-left">
							<%= image_tag("https://s3.amazonaws.com/failboard/nopreviousfail.png") %>
						</div>
				  	<% end %>
				  <% if Fail.last.id != @fail.id %>
						<div class="pull-right">
							<%= link_to image_tag("https://s3.amazonaws.com/failboard/nextfail.png"), @fail.next %>
						</div>
						<br /><br />
					<% else %>
						<div class="pull-right">
							<%= image_tag("https://s3.amazonaws.com/failboard/nonextfail.png") %>
						</div>
						<br /><br />
				  <% end %>
			</p>
			
			<div class="span7">
					<% if current_user == @fail.user %>
					<hr></hr>
					<table border="0" bordercolor="" style="background-color:" width="250px" cellpadding="3" cellspacing="3">
						<tr>
							<td><%= link_to 'Edit This Fail', edit_fail_path(@fail), class: "btn btn-small btn-warning" %></td>
							<td><%= link_to 'Delete This Fail', @fail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %></td>
						</tr>
					</table>
						<br /><br />
					<% end %><br /><br />


<br /><br />
			</div>
			</center>



			<center>



								<% if @fail.up_votes > 0 %>
										<% if @fail.up_votes == 1 %>
												<div class="arrow_box"><%= @fail.up_votes %></div><br />
													<p>Person has LOL'd at this #FAIL!</p>
											<% else %>
												<div class="arrow_box"><%= @fail.up_votes %></div><br />
													<p>People have LOL'd at this #FAIL!</p>
										<% end %>
								<% else %>
										<p>Be first to LOL at this!</p>
								<% end %>

						</div>
						</div>
					</div>
					<div class="span6 offset3">
						<center><%= link_to 'Go back to the #Failboard', fails_path, class: "btn btn-large btn-success" %></center>
					</div>
			</center>

		</div>

	</div>
	<br /><br />
	<div class="span6 offset7">
		<%= content_tag(:div, nil, :class => 'fb-comments', "data-href" => "#{request.protocol}#{request.host_with_port}#{request.fullpath}", "data-width" => '470', "data-num-posts" => "10"  ) %>
	</div>
		<div id="fb-root"></div>


	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=534777629886814";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
	</script>	
</div>