config/routes.rb
Failboard::Application.routes.draw do
  
  get "albums/new"

  get "users/show"

  break if ARGV.join.include? 'assets:precompile'
  ActiveAdmin.routes(self)

  
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :albums do
  get 'tags/:tag', to: 'fails#index', as: :tag
  resources :fails do
      member do
        post :up_vote
      end
  end

 
  end

  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'albums#index'

  match '/about',     to: 'pages#about'
  match '/fails',     to: 'fails#index'
  match '/new-fail',  to: 'fails#new'
  match 'users/:id',  to: 'users#show', :as => :user
  match '/new-album', to: 'albums#new'

end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :name, :image, :image_url, :created_at

	belongs_to :user
  has_many :fails, dependent: :destroy


  mount_uploader :image, ImageUploader
 

	validates            :user_id, presence: true
	validates            :image, presence: true
 	validates            :name, presence: true, length: { :maximum => 50 }



    before_save :update_attachment_attributes
   
    def update_attachment_attributes
      if image.present? && image_changed?
        #self.content_type = image.file.content_type 
        #self.file_size = image.file.size
      end
    end

    def next
    	user.fails.where("id > ?", id).order("id ASC").first
  	end

  	def prev
    	user.fails.where("id < ?", id).order("id DESC").first
  	end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /albums
  # GET /albums.json
  def index
     @albums = Album.order("created_at desc").page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    @albums_count = Album.count
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = current_user.albums.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = current_user.albums.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to  @album,  notice: 'You created a #Album. Now share your #album around the internets' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @Album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = current_user.albums.find(params[:id])

    respond_to do |format|
      if @Album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @Album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = current_user.albums.find(params[:id])
    @Album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  def up_vote
    @album = Album.find params[:id]
    current_user.up_vote(@album)
    redirect_to album_path(@album)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.erb
<div class="box">

		<center><img src="https://s3.amazonaws.com/failboard/tack.png" id="tack" /></center><br />

	<center>
		<strong><p style="font-size: 16px;"><u><%= album.name %></u></p></strong>

		<%= link_to (image_tag album.image), album %>

	</center>
  <p>Posted by  <%= link_to album.user.name, album.user %></p>

</div>

app/views/albums/index.html.erb
<% if !user_signed_in? %>
<br />
<center><%= image_tag("https://s3.amazonaws.com/failboard/failboard.png") %></center><br />
<% end %>


<div id="fails">
  <%= render @albums %>
</div>

<%= paginate @albums %>

app/views/albums/new.html.erb
<div class="formfail">
  <center>
    <% if params[:action] == "new" %>
         <h1>New Album</h1><br />
    <% else %>
         <h1>Edit Album</h1><br />
    <% end %>
    
      <%= simple_form_for(@album) do |f| %>

            <%= f.error_notification %>
            <%= f.full_error :image_file_size, class: "alert alert-error" %>
            <%= f.full_error :image_content_type, class: "alert alert-error" %>


            <strong><p>Name of Album</p></strong>
            <%= f.input :name, label: "" %><br />
            
            <strong><p>Upload an Album Image</p></strong>
            <%= f.input :image, label: "" %><br />

            <div class="form-actions">
              <%= f.button :submit, class: "btn btn-primary" %>
            </div>

      <% end %>
  </center>
</div>

app/views/albums/show.html.erb
<div class="row">
	<div class="span6 offset2">
		<div class="boxtwo">
			
			<center>
				    <b><u><p style="font-size:22px;"><%= @album.name %></p></u></b>
				    <%= image_tag @album.image %>
					<div class="span7">
							<% if current_user == @album.user %><br />
							<table border="0" bordercolor="" style="background-color:" width="250px" cellpadding="3" cellspacing="3">
								<tr>
									<td><%= link_to 'Edit This album', edit_album_path(@album), class: "btn btn-small btn-warning" %></td>
									<td><%= link_to 'Delete This album', @album, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %></td>
								</tr>
							</table>

							<% end %>

					</div>
			</center>


		</div>

		<center><%= link_to 'Add Photos', "/albums/#{@album.id}/fails/new", class: "btn btn-large btn-success" %></center>

	</div>

</div>