config/routes.rb
Failboard::Application.routes.draw do
  
  get "albums/new"

  get "users/show"

  break if ARGV.join.include? 'assets:precompile'
  ActiveAdmin.routes(self)

  
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :albums do
  get 'tags/:tag', to: 'fails#index', as: :tag
  resources :fails do
      member do
        post :up_vote
      end
  end

 
  end

  post "zencoder-callback" => "zencoder_callback#create", :as => "zencoder_callback"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'albums#index'

  match '/about',     to: 'pages#about'
  match '/fails',     to: 'fails#index'
  match '/new-fail',  to: 'fails#new'
  match 'users/:id',  to: 'users#show', :as => :user
  match '/new-album', to: 'albums#new'

end

app/views/layouts/_footer.html.erb
    <div class="footer">
    	<div class="well">
	       <small>Footer Content</small>
	       

   		</div>
    </div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to image_tag("https://s3.amazonaws.com/failboard/logofail2.png"), root_path, :class => 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
         <ul class="nav">
             <li><%= link_to "Home", root_path %></li>
             <li><%= link_to "About", about_path %></li>
             <li><%= link_to "Albums", albums_path %></li>
             <li></li>
         </ul>
         <ul class="nav">
          <li><a href="/albums/new"><button class="btn btn-success">Add an Album</button></a></li>
          <li><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Finfinite-bastion-8143.herokuapp.com&amp;send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=21&amp;appId=534777629886814" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:75px; height:21px; float: center; padding-top: 20px;" allowTransparency="true"></iframe></li>
         </ul>
         
          <ul class="nav pull-right">
            <% if user_signed_in? %> 
              <button class="btn btn-info dropdown-toggle" data-toggle="dropdown"><%= current_user.name %>
                  <span class="caret"></span>
              </button>
                <ul class="dropdown-menu">
                  <!-- dropdown menu links -->
                  <li><%= link_to("My Albums", current_user) %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
            <% else %>
            <ul class="nav">
              <li style="padding-top: 10px;"><%= link_to image_tag("https://s3.amazonaws.com/failboard/fblogin.png"), user_omniauth_authorize_path(:facebook)%></li>
              <li><a href="/users/sign_in"><button class="btn btn-info btn-primary">Login</button></a></li>
            </ul>
            <% end %>
         </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#Failboard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <meta property="og:image" content="https://failboard.s3.amazonaws.com/failboard/fail/image/14/tatooine.jpg?AWSAccessKeyId=AKIAIILBLZ2OJVD56EIQ&Signature=iMcsNessMId1CPwCnD%2BY2D8C6W4%3D&Expires=1362818901"/>
  <meta property="og:title" content="#Failboard"/>
  <meta property="og:description" content="Hilarious #Fail Pictures from around the web">
  <meta property="og:url" content="http://infinite-bastion-8143.herokuapp.com"/>
  <meta property="og:site_name" content="#Failboard"/>
  <meta property="og:type" content="profile"/>
  <script type="text/javascript">var switchTo5x=true;</script>
  <script type="text/javascript" src="js/jquery.social.share.2.0.min.js"></script>
  <link rel="stylesheet" type="text/css" href="css/social.css" media="all" />
  <%= csrf_meta_tags %>
</head>
<body>


    <%= render 'layouts/header' %>
     
     <div class="container">
     	<% flash.each do  |name, msg| %>
     		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
     	<% end %>
        <%= yield %>

 <%= debug(params) if Rails.env.development? %>

    </div>
  <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
</body>
</html>